### ISSUE TITLE
[Bug]: Faros CLI is broken on macOS

### ISSUE THREAD

**Issue by Jeff-Meadows** [faros-ai/faros-events-cli#105]
**Describe the bug 🐛**

A recent refactor includes the use of `declare -g` which isn't supported on macOS (at least on the default macOS installation of zsh), which causes incorrect event payloads to be sent to Faros server.

**Steps to reproduce the behavior 🕹**

1. Try to send any event to Faros from a Mac.
2. Observe one warning per flag you passed to the CLI
3. Observe the CLI try to send a bogus, barebones event payload.
4. Observe that get rejected by schema validation on the server.

**Expected behavior 🤖**

I expect to be able to send events to Faros from a Mac. I currently send them as part of iOS builds which must take place on macOS.

**Screenshots 🔦**

![image](https://github.com/faros-ai/faros-events-cli/assets/3839339/f396e007-6414-42c1-9b0b-2e11a8a1aec2)

**Comment by Jeff-Meadows** [comment]
I think this was caused by #102

**Comment by willmarks** [comment]
Hi @Jeff-Meadows, I just release v0.6.8 that should fix this issue. Please give that a try!
